# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-13 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20190413_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='users_app.books'),
        ),
    ]
