# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-14 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_auto_20190413_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='something about note'),
            preserve_default=False,
        ),
    ]
